### ISSUE TITLE
Support IDE 

### ISSUE THREAD

**Issue by trihtm** [yaapis/Theme#10]
After installing & using this package, PhpStorm can't go to the file directly by pressing the name of the views.

`
return view('pages.notifications.jobIndex', [
			'entries' => $entries
		]);
`

Who knows how to fix this?

**Comment by yaapis** [comment]
Hi, trihtm. You can configure Laravel plugin for PhpStorm to setup correct path for views:
http://joxi.ru/nAyzLLvuXDZaOr
As result: http://joxi.ru/V2VnRRbu0Rw8L2

**Comment by trihtm** [comment]
@yaapis oh very nice, could you update README? I think it's very helpful for new guys.

**Comment by yaapis** [comment]
I think ur issue not realy relative to this package =)
But I'll merge your request, if any..
