### ISSUE TITLE
5.4 Compatibility

### ISSUE THREAD

**Issue by snipe** [yaapis/Theme#11]
Hi there - is there any plan to make this package compatible with Laravel 5.4? `$this->app->share` was removed from 5.4, and needs to instead use singletons. I can work on a PR for this if you'd be willing to accept it, and if you don't think you'll have time to work on it yourself. 

Thanks!

**Comment by yaapis** [comment]
Sorry man, I have no projects on 5.4 yet =)
But yes, I'll accept PR asap.

**Comment by sroutier** [comment]
+1

**Comment by snipe** [comment]
From what I can tell, specifically, I think the `ThemeServiceProvider.php` code that looks like this:

```
// init theme with default finder
        $this->app['theme'] = $this->app->share(function($app) {
            $theme = new Theme($app, $this->app['view']->getFinder());
            return $theme;
        });
```

Should look something like this:

```
$this->app->singleton(Theme::class, function ($app) {
     return new Theme($app, $this->app['view']->getFinder());
});

// commands
        $this->app->singleton(Theme::class, function ($app) 
        {
            return new Commands\ThemeGeneratorCommand($app['config'], $app['files']);
        });

        $this->app->singleton(Theme::class, function ($app) 
        {
            return new Commands\ThemeDestroyCommand($app['config'], $app['files']);
        });
```

But I still have to do some testing. (We're upgrading from 5.2 to 5.4, so lots of things are breaking and it's hard to tell where. :P )

Let me poke around a little more and see if I can get this working. If so, I'll submit a PR.

**Comment by snipe** [comment]
I've submitted a PR for this issue: https://github.com/yaapis/Theme/pull/12

**Comment by yaapis** [comment]
@snipe Thx alot =)
https://github.com/yaapis/Theme/tree/2.3.0
