### ISSUE TITLE
Unused params in theme initialisation

### ISSUE THREAD

**Issue by SpinyMan** [yaapis/Theme#13]
My config:
'containerDir' => [
		'layout'  => 'layouts',
		'partial' => 'partials',
		'view'    => 'templates', // <-- as you can see I changed default directory placement
	]

But in the function 'Init' you continue to use default 'view' directory:
$this->finder->addLocation($path . '/' . $theme . '/views');

I suppose you have to change it to: 
config('theme.containerDir.view')

**Comment by SpinyMan** [comment]
Could u pls change
`$this->finder->addLocation($path . '/' . $theme . '/views');`
 to this one:
`$this->finder->addLocation($path . '/' . $theme . '/' . config('theme.containerDir.view'));`
and update packagist?

**Comment by yaapis** [comment]
Thx for notice.
Fixed in https://github.com/yaapis/Theme/tree/2.4.0
