### ISSUE TITLE
Theme default not found [YAAP\Theme\Exceptions\ThemeException] 

### ISSUE THREAD

**Issue by ztvMark** [yaapis/Theme#14]
When i create a theme from cli
`php artisan theme:create default
`
I get this error

```
[YAAP\Theme\Exceptions\ThemeException]  
  Theme default not found. 
```
on laravel 5.4

**Comment by yaapis** [comment]
Sorry, but I cannot reproduce your issue.
http://joxi.ru/DmB4jdKtGg5MAP
This is on laravel 5.4 clean installation.
Could you add some more information about the error?

**Comment by yaapis** [comment]
I'll close this issue for now. Fell free to reopen it if you want to.
